DROP TABLE IF EXISTS COUNTERS;
DROP TABLE IF EXISTS CASSETTES;

	CREATE TABLE CASSETTES (
	  ID INT,
	  NAME VARCHAR(255) NOT NULL,
	  DESCRIPTION VARCHAR(255),
	  TYPE ENUM('Recycling','In','RetractReject'),
	  PRIMARY KEY (ID)
	);

	CREATE TABLE COUNTERS (
	  ID INT AUTO_INCREMENT,
	  NAME VARCHAR(255) NOT NULL,
	  VALUEe INT,
	  CASSETTE_ID INT,
	  PRIMARY KEY (ID),
      CONSTRAINT cassette_id FOREIGN KEY (CASSETTE_ID) REFERENCES CASSETTES(ID)
	);

INSERT INTO CASSETTES (ID, NAME, DESCRIPTION, TYPE) VALUES
	  (4301, 'Main cassette', 'cassette, designed for tests', 'In');

INSERT INTO COUNTERS (NAME, VALUEe, CASSETTE_ID) VALUES
   	  ('4301 counter for 5000', 5000, 4301),
   	  ('4301 counter for 1000', 1000, 4301),
      ('4301 counter for 500', 500, 4301),
      ('4301 counter for 100', 100, 4301);